apiVersion: apps/v1
kind: Deployment
metadata:
  name: s09s12-web
spec:
  replicas: 1
  selector:
    matchLabels: { app: s09s12-web }
  template:
    metadata:
      labels: { app: s09s12-web }
    spec:
        securityContext:
            runAsNonRoot: true
      containers:
        - name: web
          image: s09s12-app:1.0.0
          ports: [{ containerPort: 8080 }]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 1000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"