name: S12 - IaC & Container Security
on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile'
      - 'iac/**'
      - '.github/workflows/ci-s12-iac-container.yml'
jobs:
  s12:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v4

      - name: Ensure evidence dirs
        run: mkdir -p EVIDENCE/S12

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/s09s12-app:ci
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Cosign sign image (keyless)
        run: cosign sign --keyless $IMAGE

      - name: Verify image signature
        run: cosign verify --keyless $IMAGE


      - name: Hadolint Dockerfile (JSON)
        run: |
          docker run --rm -i hadolint/hadolint hadolint -f json - < Dockerfile > EVIDENCE/S12/hadolint.json || true

      - name: Checkov (iac/)
        run: |
          docker run --rm -v $PWD:/src bridgecrew/checkov:latest -d /src/iac -o json > EVIDENCE/S12/checkov.json || true
      - name: Trivy image (JSON)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 's09s12-app:ci'
          format: 'json'
          output: 'EVIDENCE/S12/trivy.json'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          
      - uses: actions/upload-artifact@v4
        with:
          name: S12_EVIDENCE
          path: EVIDENCE/S12
