name: S12 - IaC & Container Security
on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile'
      - 'iac/**'
      - '.github/workflows/ci-s12-iac-container.yml'
jobs:
  s12:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Ensure evidence dirs
        run: mkdir -p EVIDENCE/S12

      - name: Build Docker image
        run: docker build -t s09s12-app:ci .

      - name: Hadolint Dockerfile (JSON)
        run: |
          docker run --rm -i hadolint/hadolint hadolint -f json - < Dockerfile > EVIDENCE/S12/hadolint.json || true

      - name: Check Hadolint thresholds
        run: |
          ERROR_COUNT=$(jq '[.[] | select(.level == "error")] | length' EVIDENCE/S12/hadolint.json)
          WARNING_COUNT=$(jq '[.[] | select(.level == "warning")] | length' EVIDENCE/S12/hadolint.json)
          
          echo "Hadolint Results: Errors=$ERROR_COUNT, Warnings=$WARNING_COUNT"
          
          # Thresholds: ERROR=0, WARNING=5
          if [ "$ERROR_COUNT" -gt 0 ]; then
            echo "::error::Hadolint threshold exceeded: $ERROR_COUNT errors found (max: 0)"
            exit 1
          fi
          
          if [ "$WARNING_COUNT" -gt 5 ]; then
            echo "::error::Hadolint threshold exceeded: $WARNING_COUNT warnings found (max: 5)"
            exit 1
          fi
          
          echo "✅ Hadolint thresholds passed"




      - name: Checkov (iac/)
        run: |
          docker run --rm -v $PWD:/src bridgecrew/checkov:latest -d /src/iac -o json > EVIDENCE/S12/checkov.json || true
      - name: Check Checkov thresholds
        run: |
          FAILED_COUNT=$(jq '.summary.failed // 0' EVIDENCE/S12/checkov.json)
          
          echo "Checkov Results: Failed=$FAILED_COUNT"
          
          # Threshold: FAILED=10
          if [ "$FAILED_COUNT" -gt 10 ]; then
            echo "::error::Checkov threshold exceeded: $FAILED_COUNT failed checks (max: 10)"
            exit 1
          fi
          
          echo "✅ Checkov thresholds passed"


      - name: Trivy image (JSON)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 's09s12-app:ci'
          format: 'json'
          output: 'EVIDENCE/S12/trivy.json'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'

      - name: Check Trivy thresholds
        run: |
          CRITICAL_COUNT=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "CRITICAL")] | length' EVIDENCE/S12/trivy.json)
          HIGH_COUNT=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "HIGH")] | length' EVIDENCE/S12/trivy.json)
          
          echo "Trivy Results: Critical=$CRITICAL_COUNT, High=$HIGH_COUNT"
          
          # Thresholds: CRITICAL=0, HIGH=5
          if [ "$CRITICAL_COUNT" -gt 0 ]; then
            echo "::error::Trivy threshold exceeded: $CRITICAL_COUNT critical vulnerabilities found (max: 0)"
            exit 1
          fi
          
          if [ "$HIGH_COUNT" -gt 5 ]; then
            echo "::error::Trivy threshold exceeded: $HIGH_COUNT high vulnerabilities found (max: 5)"
            exit 1
          fi
          
          echo "✅ Trivy thresholds passed"

      

#       COSIGNING with PUSH TO GHCR
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/s09s12-app:ci
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Cosign sign image (keyless)
        run: cosign sign -y $IMAGE

      - name: Verify image signature
        run: cosign verify --certificate-identity-regexp "https://github.com/${{ github.repository }}" --certificate-oidc-issuer "https://token.actions.githubusercontent.com" $IMAGE > EVIDENCE/S12/attestation.json

      - uses: actions/upload-artifact@v4
        with:
          name: S12_EVIDENCE
          path: EVIDENCE/S12